### ISSUE TITLE
Docstrings from `pydantic.dataclasses` are not retrieved by Tyro

### ISSUE THREAD

**Issue by emaheuxPEREN** [brentyi/tyro#312]
## Example code

```python
from dataclasses import is_dataclass

import tyro
from pydantic import ConfigDict
from pydantic.dataclasses import dataclass
from pydantic.version import version_info


@dataclass(config=ConfigDict(use_attribute_docstrings=True))  # does not work either without this flag
class A:
    """Tyro retrieves this docstring"""

    x: str
    """But not this one (unlike when using a standard dataclass)"""


assert is_dataclass(A)
print(version_info())
tyro.cli(A)
```

### Versions

```yaml
                         tyro: 0.9.23
             pydantic version: 2.11.5
        pydantic-core version: 2.33.2
               python version: 3.13.3
             related packages: typing_extensions-4.14.0
```

## Expected result

Parameter `x` has its description filled with its docstring.

## Actual result

Description for parameter `x` is left empty unlike for standard dataclass.
